[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
reqwest = "0.13.4"
postcard = "1.1.3"
gtfs_rt_decode = "0.1.2"
prost = "0.14.4"
csv = "1.4.0"
serde = { version = "1.0.229", features = ["derive", "std"] }
zip = "8.6.0"
itertools = "0.15.0"
futures = "0.3.34"
serde_norway = "0.9.42"
log = { version = "0.4.34", features = ["kv"] }
colog = "1.4.0"
